media:
  input: content/images
  output: /images
content:
  - name: pages
    label: Pages
    type: collection
    path: content
    subfolders: false
    format: yaml-frontmatter
    exclude:
      - 404.md
    fields:
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - name: title
            label: Titre
            type: string
            required: true
          - name: order
            label: "Position dans le menu : 1 en premier, 2 en second..."
            type: number
            required: true
      - name: body
        type: rich-text
    view:
      fields:
        - eleventyNavigation.order
        - eleventyNavigation.title
      primary: eleventyNavigation.title
      sort:
        - eleventyNavigation.order
