media:
  input: content/images
  output: /images
content:
  - name: pages
    label: Pages
    type: collection
    path: content
    subfolders: false
    format: yaml-frontmatter
    fields:
      - name: body
        type: rich-text
